/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Admin;

import Entity.Product;
import Repository.ProductRepo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ash
 */
public class PanelProducts extends javax.swing.JPanel {

    /**
     * Creates new form PanelUpdateData
     */
    ProductRepo pr;
    ArrayList<Product> products;
    public PanelProducts() {
        initComponents();
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        
        nameTf.setVisible(false);
        categoryTf.setVisible(false);
        priceTf.setVisible(false);
        
        confirmNewProduct.setVisible(false);
        confirmProductEdit.setVisible(false);
        
        products = new ArrayList<Product>();
        
        pr = new ProductRepo();
        
        updateTableData();
        
        
    }
    
    public void updateTableData(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        products.clear();
        model.setRowCount(0);
        products = pr.allAvailableProduct();
        
        for(int i=0;i<products.size();++i){
            model.addRow(tableRowData(products.get(i)));
        }
    }
    
    public Object[] tableRowData(Product product){
        Object[] rowdata = {product.getName(),product.getCategory(),product.getPrice()};
        return rowdata;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        removeBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        nameTf = new javax.swing.JTextField();
        categoryTf = new javax.swing.JTextField();
        priceTf = new javax.swing.JTextField();
        confirmNewProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        confirmProductEdit = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1100, 700));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Category", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        removeBtn.setText("Remove Product");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Add New Product");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        confirmNewProduct.setText("Done");
        confirmNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNewProductActionPerformed(evt);
            }
        });

        jLabel1.setText("Name :");

        jLabel2.setText("Category :");

        jLabel3.setText("Price :");

        editBtn.setText("Edit Product");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        confirmProductEdit.setText("Done");
        confirmProductEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmProductEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addBtn)
                                .addGap(18, 18, 18)
                                .addComponent(editBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryTf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(confirmNewProduct)
                                        .addGap(18, 18, 18)
                                        .addComponent(confirmProductEdit))
                                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(removeBtn))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(addBtn)
                                            .addComponent(editBtn))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(5, 5, 5)
                                        .addComponent(categoryTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addGap(5, 5, 5)
                                .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmNewProduct)
                            .addComponent(confirmProductEdit))))
                .addGap(18, 18, 18)
                .addComponent(removeBtn)
                .addContainerGap(210, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        
        nameTf.setVisible(true);
        categoryTf.setVisible(true);
        priceTf.setVisible(true);
        
        confirmNewProduct.setVisible(true);
        
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void confirmNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNewProductActionPerformed
        // TODO add your handling code here:
        Product product = new Product(nameTf.getText(), categoryTf.getText(), Double.parseDouble(priceTf.getText().toString()));
        pr.updateProduct(product);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        
        nameTf.setVisible(false);
        categoryTf.setVisible(false);
        priceTf.setVisible(false);
        
        confirmNewProduct.setVisible(false);
        
    }//GEN-LAST:event_confirmNewProductActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        
        nameTf.setVisible(true);
        categoryTf.setVisible(true);
        priceTf.setVisible(true);
        
        confirmProductEdit.setVisible(true);
        
        nameTf.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        categoryTf.setText(model.getValueAt(jTable1.getSelectedRow(), 1).toString());
        priceTf.setText(model.getValueAt(jTable1.getSelectedRow(), 2).toString());
        
        
    }//GEN-LAST:event_editBtnActionPerformed

    private void confirmProductEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmProductEditActionPerformed
        // TODO add your handling code here:
        Product product = new Product(nameTf.getText(), categoryTf.getText(), Double.valueOf(priceTf.getText()));
        pr.updateProduct(product);
        updateTableData();
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        
        nameTf.setVisible(false);
        categoryTf.setVisible(false);
        priceTf.setVisible(false);
        
        confirmProductEdit.setVisible(false);
    }//GEN-LAST:event_confirmProductEditActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        Product product = new Product();
        product.setName(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        
        pr.deleteProduct(product);
        updateTableData();
    }//GEN-LAST:event_removeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField categoryTf;
    private javax.swing.JButton confirmNewProduct;
    private javax.swing.JButton confirmProductEdit;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameTf;
    private javax.swing.JTextField priceTf;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
